import type { Patient } from './ehr-types'

export const SAMPLE_PATIENTS: Patient[] = [
  {
    id: 'exp-001',
    expedienteNumber: 'VIV-2024-001',
    createdAt: '2024-03-15T10:00:00Z',
    updatedAt: '2026-04-18T09:30:00Z',
    generalData: {
      nombre: 'María',
      apellidoPaterno: 'González',
      apellidoMaterno: 'Reyes',
      fullName: 'María González Reyes',
      birthDate: '1985-06-12',
      sex: 'femenino',
      curp: 'GORM850612MNLNYR08',
      phone: '81 2345 6789',
      email: 'maria.gonzalez@gmail.com',
      address: 'Av. Constitución 1540, Col. Obispado, Monterrey, N.L.',
    },
    familyHistory: {
      notes: 'Madre con diabetes mellitus tipo 2 e hipertensión arterial. Padre con rinitis alérgica crónica. Abuela materna con hipoacusia bilateral.',
      relevantConditions: ['Diabetes mellitus tipo 2', 'Hipertensión arterial', 'Rinitis alérgica', 'Hipoacusia familiar'],
    },
    personalHistory: {
      pathological: 'Rinitis alérgica desde los 12 años. Amigdalectomía a los 8 años. Sin hospitalizaciones previas relevantes.',
      allergies: ['Polen', 'Polvo doméstico', 'Penicilina (urticaria)'],
      currentMedications: [
        { name: 'Loratadina 10mg', dose: '1 tableta', frequency: 'cada 24 horas', indication: 'rinitis alérgica' },
        { name: 'Fluticasona spray nasal', dose: '2 aplicaciones por fosa nasal', frequency: 'cada 24 horas', indication: 'rinitis alérgica' },
      ],
      nonPathological: 'Tabaquismo negado. Alcoholismo social ocasional. Sedentaria.',
    },
    nom024Data: { paisNacimiento: 142, entidadNacimiento: null, sexoCurp: null, sexoBiologico: null, genero: null, derechohabiencia: null, seConsideraIndigena: null, seAutodenominaAfromexicano: null, migrante: null, paisProcedencia: null },
  },
  {
    id: 'exp-002',
    expedienteNumber: 'VIV-2024-008',
    createdAt: '2024-07-22T11:00:00Z',
    updatedAt: '2026-04-10T14:20:00Z',
    generalData: {
      nombre: 'Carlos',
      apellidoPaterno: 'Mendoza',
      apellidoMaterno: 'Ortiz',
      fullName: 'Carlos Mendoza Ortiz',
      birthDate: '1972-11-03',
      sex: 'masculino',
      curp: 'MEOC721103HNLNRL07',
      phone: '81 9876 5432',
      email: 'c.mendoza@hotmail.com',
      address: 'Calle Hidalgo 320, Col. Centro, San Pedro Garza García, N.L.',
    },
    familyHistory: {
      notes: 'Sin antecedentes heredofamiliares de relevancia para el padecimiento actual.',
      relevantConditions: [],
    },
    personalHistory: {
      pathological: 'Hipertensión arterial sistémica en tratamiento desde 2019. Sin cirugías previas.',
      allergies: [],
      currentMedications: [
        { name: 'Losartán 50mg', dose: '1 tableta', frequency: 'cada 24 horas', indication: 'hipertensión arterial' },
      ],
      nonPathological: 'Tabaquismo 10 años, suspendido hace 5 años. Ingesta de alcohol moderada los fines de semana.',
    },
    nom024Data: { paisNacimiento: 142, entidadNacimiento: null, sexoCurp: null, sexoBiologico: null, genero: null, derechohabiencia: null, seConsideraIndigena: null, seAutodenominaAfromexicano: null, migrante: null, paisProcedencia: null },
  },
  {
    id: 'exp-003',
    expedienteNumber: 'VIV-2025-015',
    createdAt: '2025-01-10T09:15:00Z',
    updatedAt: '2026-03-20T16:00:00Z',
    generalData: {
      nombre: 'Ana Sofía',
      apellidoPaterno: 'Torres',
      apellidoMaterno: 'Villarreal',
      fullName: 'Ana Sofía Torres Villarreal',
      birthDate: '1998-04-25',
      sex: 'femenino',
      curp: 'TOVA980425MNLRLN09',
      phone: '81 1122 3344',
      email: 'ana.torres@outlook.com',
      address: 'Av. Lázaro Cárdenas 2400, Col. Residencial San Agustín, Monterrey, N.L.',
    },
    familyHistory: {
      notes: 'Madre y hermano mayor con rinitis alérgica. Padre con asma bronquial.',
      relevantConditions: ['Rinitis alérgica', 'Asma bronquial'],
    },
    personalHistory: {
      pathological: 'Rinitis alérgica desde la infancia. Dermatitis atópica en remisión. Sin cirugías.',
      allergies: ['Ácaros del polvo', 'Epitelio de gato'],
      currentMedications: [],
      nonPathological: 'Niega tabaquismo y alcoholismo. Activa físicamente.',
    },
    nom024Data: { paisNacimiento: 142, entidadNacimiento: null, sexoCurp: null, sexoBiologico: null, genero: null, derechohabiencia: null, seConsideraIndigena: null, seAutodenominaAfromexicano: null, migrante: null, paisProcedencia: null },
  },
  {
    id: 'exp-004',
    expedienteNumber: 'VIV-2025-031',
    createdAt: '2025-06-01T08:00:00Z',
    updatedAt: '2026-04-05T10:10:00Z',
    generalData: {
      nombre: 'Roberto',
      apellidoPaterno: 'Silva',
      apellidoMaterno: 'Cárdenas',
      fullName: 'Roberto Silva Cárdenas',
      birthDate: '1968-09-17',
      sex: 'masculino',
      curp: 'SICR680917HNLLBT04',
      phone: '81 5566 7788',
      email: 'rsilva@empresa.com',
      address: 'Privada Eucalipto 8, Fracc. Los Pinos, Guadalupe, N.L.',
    },
    familyHistory: {
      notes: 'Padre con hipoacusia bilateral de inicio en la quinta década. Madre sana.',
      relevantConditions: ['Hipoacusia de inicio tardío'],
    },
    personalHistory: {
      pathological: 'Diabetes mellitus tipo 2 diagnosticada en 2020, controlada con metformina. Sin cirugías previas.',
      allergies: [],
      currentMedications: [
        { name: 'Metformina 850mg', dose: '1 tableta', frequency: 'cada 12 horas con alimentos', indication: 'diabetes mellitus tipo 2' },
      ],
      nonPathological: 'Exposición laboral a ruido en planta industrial por más de 15 años. Usa protección auditiva desde hace 3 años.',
    },
    nom024Data: { paisNacimiento: 142, entidadNacimiento: null, sexoCurp: null, sexoBiologico: null, genero: null, derechohabiencia: null, seConsideraIndigena: null, seAutodenominaAfromexicano: null, migrante: null, paisProcedencia: null },
  },
  {
    id: 'exp-005',
    expedienteNumber: 'VIV-2026-002',
    createdAt: '2026-01-08T13:30:00Z',
    updatedAt: '2026-04-15T11:45:00Z',
    generalData: {
      nombre: 'Lucía',
      apellidoPaterno: 'Ramírez',
      apellidoMaterno: 'Fuentes',
      fullName: 'Lucía Ramírez Fuentes',
      birthDate: '1990-02-14',
      sex: 'femenino',
      curp: 'RAFL900214MNLMCC04',
      phone: '81 3344 5566',
      email: 'lucia.ramirez@gmail.com',
      address: 'Calle Morelos 678, Col. San Jerónimo, Monterrey, N.L.',
    },
    familyHistory: {
      notes: 'Sin antecedentes familiares de relevancia.',
      relevantConditions: [],
    },
    personalHistory: {
      pathological: 'Sin antecedentes patológicos de importancia. Sin cirugías previas.',
      allergies: ['AINE (naproxeno — broncoespasmo)'],
      currentMedications: [],
      nonPathological: 'No fuma. No consume alcohol. Practica yoga 3 veces por semana.',
    },
    nom024Data: { paisNacimiento: 142, entidadNacimiento: null, sexoCurp: null, sexoBiologico: null, genero: null, derechohabiencia: null, seConsideraIndigena: null, seAutodenominaAfromexicano: null, migrante: null, paisProcedencia: null },
  },
]
