export { DocumentList } from './DocumentList'
export { PrescriptionDetail } from './PrescriptionDetail'
export { ConsentFormDetail } from './ConsentFormDetail'
export { EvolutionNoteForm } from './EvolutionNoteForm'
export { PrescriptionForm } from './PrescriptionForm'
